### ISSUE TITLE
How do i print a bitmap image logo on a M5Dial Display ?

### ISSUE THREAD

**Issue by RiteshK551** [m5stack/M5Dial#10]
Hello,

I am trying to print a logo bitmap on a M5Dial Display, Unable to print
Other text and simple features i am able to do

this is the code

#include <M5Dial.h>

const uint8_t smiley_bmp[] = {
0b00111100,
0b01000010,
0b10100101,
0b10000001,
0b10100101,
0b10011001,
0b01000010,
0b00111100};

void setup() {
M5.begin();
M5.Lcd.begin();
M5.Lcd.setRotation(1);
}

void loop() {
// Draw the bitmap at position (0, 0)
M5.Lcd.drawBitmap(0, 0, 8, 8, smiley_bmp);
delay(5000);
}

**Comment by imliubo** [comment]
Hi @RiteshK551 ,

**drawBitmap** is deprecated, please try this way:
```C
auto bpp = (lgfx::color_depth_t)1;
auto forecolor = 0xFFFF;
auto backcolor = 0x0000;
gfx.pushGrayscaleImage(0, 0, 8, 8, smiley_bmp, bpp, forecolor, backcolor);
```
Here are the results: 
![image](https://github.com/m5stack/M5Dial/assets/26544331/dc675f48-faa6-4d73-8e38-c895c856da96)

**Comment by imliubo** [comment]
Closed for now, feel free to reopen.
