### ISSUE TITLE
How to control LCD backlight on/off

### ISSUE THREAD

**Issue by gdivry** [m5stack/M5Dial#13]
Hello
why do i have to put the pin 9 high to light the screen ?

Sincerely 
Gery

**Comment by gdivry** [comment]
to complete, i use the STAMPS board configuration because the M5stampS3 board config refuse to upload code

**Comment by imliubo** [comment]
Hi @gdivry ,

Pin 9 is LCD backlight control pin, here is the [schematic](https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/docs/products/core/M5Dial/Sch_M5Dial.pdf), 
<img width="966" alt="image" src="https://github.com/m5stack/M5Dial/assets/26544331/56b140e5-dbb4-49a8-9d32-d409b9cbdad4">
Q1 in the picture is NMOS. When you set LCD_BL(Pin 9) to high level, the LCD backlight will be lit.

**Comment by imliubo** [comment]
Closed for now, feel free to reopen.
