### ISSUE TITLE
Is the as-shipped User Demo source code available?

### ISSUE THREAD

**Issue by teastainGit** [m5stack/M5Dial#2]
The Demo is brilliant and I would like to use many elements in my new ThermoStat sketch.
cheers -Terry

**Comment by teastainGit** [comment]
Answered by felmue on the community site.

I am disappointed that it is not Arduino IDE and was not posted on the main Dial (this one) GitHub repository. What feature required ESP-IDF?
-Terry

**Comment by martinglass** [comment]
> Answered by felmue on the community site.
> 
> I am disappointed that it is not Arduino IDE and was not posted on the main Dial (this one) GitHub repository. What feature required ESP-IDF? -Terry

https://github.com/m5stack/M5Dial-UserDemo
