### ISSUE TITLE
Impossible to display images with UIFlow2

### ISSUE THREAD

**Issue by JeanFabreAtHutongGames** [m5stack/M5Dial#21]
Battling for quite some time now, and I can't find a way to make the image files I upload on UIFLOW to show on the device. They do get shown in the UIFLOW interface fine, I do put a flow node to show that image in the visual code and I can see it also in the editor. no error is given back as far as I can see.  I tried different format and extension based on what I could find on the internet.

unfortunatly, I can not find any actual working example nor video tutorial, surely, I am missing the obvious here... any help would be appreciated, at this point, I treat it as an issue which is why I am reporting here.

thanks,

Jean

**Comment by JeanFabreAtHutongGames** [comment]
ok, finally, got to the bottom of this: https://docs.m5stack.com/en/uiflow2/projects/file_manager indeed all is good, it's simply a problem of feedback from the UIFlow interface and code execution that doesn't mention it's missing the file, so you are left wondering why the wysiwyg is deceptive in this case. All is good, images have to be downloaded manually on the device. https://community.m5stack.com/topic/6831/core-s3-se-images-won-t-show/11

**Comment by kzim200** [comment]
Have you had problems with the M5 Dial suddenly quit showing images?  I have had to erase and reflash my several times, then upload the code and images.  Kinda a pain to do it multiple times.
